USE DB_PACOTES_TURISTICOS;

INSERT INTO TB_USER(EMAIL, SENHA, IS_ADM) VALUES ('admin', 'admin', TRUE);
INSERT INTO TB_AGENCIA_TURISMO(ID_USER, CNPJ, NOME, DESCRICAO) VALUES (1, '100', 'Agencia_Admin', 'Agencia do admin');
INSERT INTO TB_PACOTE_TURISTICO(ID_AGENCIA, DATA_PARTIDA, DATA_CHEGADA, VALOR, DESCRICAO) VALUES (1, '2021-1-01', '2021-2-01', 500.00, 'Primeiro pacote');