USE DB_PACOTES_TURISTICOS;

INSERT INTO TB_AGENCIA_TURISMO(EMAIL, SENHA, IS_ADM, CNPJ, NOME, DESCRICAO) VALUES ('admin', 'admin', 'ADM', '100', 'Agencia_Admin', 'Agencia do admin');
INSERT INTO TB_CLIENTE(EMAIL, SENHA, CPF, IS_ADM, NOME, TELEFONE, SEXO, DATA_NASC) VALUES ('admin', 'admin', '100', 'ADM', 'Julio', '9999', 'Masculino', '2001-4-27');

INSERT INTO TB_PACOTE_TURISTICO(ID_AGENCIA, DATA_PARTIDA, DATA_CHEGADA, VALOR, DESCRICAO) VALUES (1, '2021-1-01', '2021-2-01', 500.00, 'Primeiro pacote');