CREATE DATABASE DB_PACOTES_TURISTICOS;

USE DB_PACOTES_TURISTICOS;

CREATE TABLE TB_CLIENTE(
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(128) NOT NULL, 
    CPF VARCHAR(14) NOT NULL UNIQUE,
    -- SIM OU NÃO
    IS_ADM VARCHAR(3) NOT NULL,
    NOME VARCHAR(300) NOT NULL, 
    TELEFONE VARCHAR(15),
    SEXO VARCHAR(50), 
    DATA_NASC VARCHAR(12), 
    PRIMARY KEY (CPF)
    
);

CREATE TABLE TB_AGENCIA(
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(128) NOT NULL, 
    CNPJ VARCHAR(50) NOT NULL UNIQUE, 
    NOME VARCHAR(300) NOT NULL, 
    DESCRICAO VARCHAR(255), 
    PRIMARY KEY (CNPJ)
);

CREATE TABLE TB_PACOTE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CNPJ_AGENCIA VARCHAR(50) NOT NULL,
    DATA_PARTIDA VARCHAR(12) NOT NULL, 
    DURACAO_DIAS BIGINT NOT NULL, 
    VALOR DOUBLE(10,2) NOT NULL, 
    DESCRICAO VARCHAR(255),
    DESTINOS VARCHAR(255),
    FOTOS VARCHAR(255),
    PRIMARY KEY (ID), 
    FOREIGN KEY (CNPJ_AGENCIA) REFERENCES TB_AGENCIA(CNPJ)
);

CREATE TABLE TB_COMPRA(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(14) NOT NULL,
    ID_PACOTE BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (CPF) REFERENCES TB_CLIENTE(CPF),
    FOREIGN KEY (ID_PACOTE) REFERENCES TB_PACOTE(ID)
);
